version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 125571554996.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t demorepo .
      - docker tag demorepo:latest 125571554996.dkr.ecr.ap-south-1.amazonaws.com/demorepo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 125571554996.dkr.ecr.ap-south-1.amazonaws.com/demorepo:latest
